### PR TITLE
Allow module description to be shown as tooltip

### PR DESCRIPTION
**Pull request by rogiervandongen**
Allow module description to be shown as tooltip.

Added:
- language(s)
- default settings
- module specific settings
- functionality in course_renderer
- JS tooptip call in mustache template (content.mustache, seerms the only and logic place here)

### CODE REVIEW

**Comment by gemguardian** [comment]
@gjb2048 could you ensure this pull request gets merged with the master? 

Rogier had to do a small change, i have tested it and it's ok for the master. 

Thank you :)

**Comment by gjb2048** [comment]
@gemguardian Do you want some of https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/actions/runs/4355721582/jobs/7612725321 addressed?  As this has been happening for me too given a Code Checker update.  The colour popup solution is to ignore the file etc.  This is because of needing non-coding standard conventions for the parent class being a third party thing in core.

**Comment by gemguardian** [comment]
@gjb2048 yes please :)

**Comment by gjb2048** [comment]
@gemguardian Have merged into master where I'll then sort the Code Checker issues.

**Comment by gjb2048** [comment]
@gemguardian Done -> https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/actions/runs/4357613818 - really odd as the files causing the issue were already excluded for the reasons stated.  Just had to change the syntax of the ignore.

**Comment by gemguardian** [comment]
@gjb2048 thank you :)

**Pull request merged**
