### PR TITLE
Wip customicons

### PR DESCRIPTION
**Pull request by rogiervandongen**
@gemguardian 
The new code as presented last friday.
Please take note: version, readme and the ipgrade files have deliberately not been updated yet.

### CODE REVIEW

**Comment by gemguardian** [comment]
@gjb2048 Could you please check the Moodle Plugin CI?

**Comment by gjb2048** [comment]
Dear @gemguardian,

Its failing because of the commented out code, such as https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/blob/13e5369627450e489974f1aa395e0e681ca71699/classes/course_renderer.php#L112-L122.

And there are other warnings too, so the Moodle Coding Standard is not being followed:

Screenshot 2023-02-13 113103


And there is an empty 'else' statement, so is this meant to be finished code or a 'work in progress'?:

Screenshot 2023-02-13 113145

G

**Comment by rogiervandongen** [comment]
@gemguardian @gjb2048 
The commented out code is a result from my work.
The CI errors caused from renderer.php are not a result of my changes (as far as I remember I haven't touched that file).
I've taken the liberty of fixing a range of errors even when not my own. new PR on it's way

**Comment by gjb2048** [comment]
Dear @rogiervandongen,

My apologies over the CI warnings in the renderer.php file.  I was mistaken, it does indeed seem like the CI / Code Checker is getting stricter since when I originally wrote that code, i.e https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/actions/runs/3905104979 - where I didn't spot the warnings.

Gareth

**Comment by rogiervandongen** [comment]
Dear @gjb2048 
No worries. While I was fixing the main issues that occured in the modified course renderer, I've fixed the rest of the CI warnings/errors as well.
I see I've missed one occurence of a 134 character line, but doubt this should be a reason to hold back a release.

**Comment by gemguardian** [comment]
@gjb2048 Since I have no idea which option to select for the Merge Pull request, would you please do the honors :)

**Comment by gjb2048** [comment]
@rogiervandongen With https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/blob/e622e683e026f8904b048a2b105b7eac1c7c2232/classes/course_renderer.php#L238-L239 - the course_renderer is used regardless of editing state.  What makes you think that code isn't called please?

**Comment by gjb2048** [comment]
Dear @gemguardian,

Done.

G

**Comment by rogiervandongen** [comment]
> @rogiervandongen With
> 
> https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/blob/e622e683e026f8904b048a2b105b7eac1c7c2232/classes/course_renderer.php#L238-L239
> 
> - the course_renderer is used regardless of editing state. What makes you think that code isn't called please?

@gjb2048 it was this bit of code that made me think so, but only under the given circumstances. It seems the custom course renderer is never in use when in editing mode (I haven't looked into it any further and more or less added the comment for myself):
https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/blob/e622e683e026f8904b048a2b105b7eac1c7c2232/classes/output/renderer.php#L84

**Comment by gjb2048** [comment]
Dear @rogiervandongen,

Thanks for that, I'd not spotted it!

And curious about https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/pull/3/commits/e6756f050ee7dcaaf085c2be101dd587e48ce785 instead of a 'rebase'?

Kind regards,

Gareth

**Comment by gemguardian** [comment]
The language file was me :)

**Comment by rogiervandongen** [comment]
> Dear @rogiervandongen,
> 
> Thanks for that, I'd not spotted it!
> 
> And curious about [e6756f0](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-format_vsf/commit/e6756f050ee7dcaaf085c2be101dd587e48ce785) instead of a 'rebase'?
> 
> Kind regards,
> 
> Gareth

Dear @gjb2048 
Thank you for spotting that! I hadn't even noticed, it was caused by merging in the changes that were done in January (I had already forked the codebase prior to this change).
I'm not 100% sure what it should be to be honest. It's a part I haven't touched codewise, but I'm assuming the "uservisible" state would be the correct one and got overwritten by synching with the master branch.

**Comment by gjb2048** [comment]
Ops!  I seem to be having 'one of those' days!  I looked at the commit log (Matilda is my Raspberry PI):

Screenshot 2023-02-13 133417

And got the wrong commit!  Saw the branching points and wondered why the development changes weren't rebased on top of the current master before merging like what happens in Moodle Tracker.  But clearly the merge algorithm was able to sort things.  Just thoughts :).

**Pull request merged**
